// Generated by scripts/generate-home-hero-placeholder.ts.
// Pre-render the filtered SVG so browsers never rasterize it at full viewport size.
export const HERO_PLACEHOLDER =
  'data:image/webp;base64,UklGRuwAAABXRUJQVlA4IOAAAAAwCACdASqAAFAAPjEYiUQiIYgyaBABglpBvgcpbIuN8AeKFXqn2fFg5D0FwhhTHK8P4o6lo8buuqJ0qoOk8uCgYESUIvbs08SJQAD+/g7H9km5uD4nsEb2hS+y2JcB1nSNsTESub2eagUan8al81BnPH5x1DIQ5voyWlCs0eBlHuKz1RjvWt/tA9tc6ThSZeCWNTH8jhCohmuY7HQ9Lw3/8woqc85SHMXMEL+lXAHRNE9bt6S1hUjinO0b1gHogdn/O+z8mCFImFaVSIli0xTHjcjMfNN68Yg24Y8U44aAAA==';
