// Run with: node --import tsx scripts/generate-home-hero-placeholder.ts
// Sharp is provided by the locked Next.js installation; this runs only when the hero changes.
import { writeFile } from 'node:fs/promises';
import sharp from 'sharp';
import { buildCloudinaryUrl } from '../src/lib/cloudinary';
import { buildCinematicBlurDataUrl } from '../src/lib/lqip';

async function main() {
  const image = buildCloudinaryUrl('creare-hero-image.jpg', {
    profile: 'hero',
    format: 'auto',
    quality: 'auto:good',
    dpr: 'auto',
  });
  const source = buildCinematicBlurDataUrl(image, { atmosphere: 'dark', profile: 'hero' });
  const svg = decodeURIComponent(source.slice(source.indexOf(',') + 1));
  const raster = await sharp(Buffer.from(svg))
    .resize(128, 80)
    .blur(2)
    .webp({ quality: 90 })
    .toBuffer();
  await writeFile(
    new URL('../src/app/home/components/hero-placeholder.ts', import.meta.url),
    '// Generated by scripts/generate-home-hero-placeholder.ts.\n' +
      '// Pre-render the filtered SVG so browsers never rasterize it at full viewport size.\n' +
      `export const HERO_PLACEHOLDER = 'data:image/webp;base64,${raster.toString('base64')}';\n`
  );
  console.log(`Hero placeholder: ${raster.length} bytes`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
